name: CI - bootcamp-devops-project1 - api - dev
on:
  push:
    branches: [ "development" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHOT_SHA: ${{ github.sha[0:8] }} # Create SHOT_SHA to image tagging 
      
    steps:
      - name: Test SHORT_SHA
        run: echo $SHORT_SHA

      - name: Checkout source code
        uses: actions/checkout@v4
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Get Tag
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT
 
      -
        name: Build and push - Api
        uses: docker/build-push-action@v5
        with:
          push: true
          file: Dockerfile
          tags: gitopsdevopsbootcamp/bootcamp-devops-api-dev:$SHOT_SHA
      
      - name: Checkout GitOps Repo
        uses: actions/checkout@v4
        with:
          repository: devops-bootcamp-sre/bootcamp-devops-gitops
          token: ${{ secrets.ACCESS_TOKEN}}

      - name: Kustomize 
        uses: imranismail/setup-kustomize@v2
      - run: |
          git config --global user.email "tt7886081@gmail.com"
          git config --global user.name "gitops-devops-bootcamp"
          cd services/bootcamp-devops-api/development
          kustomize edit set image gitopsdevopsbootcamp/bootcamp-devops-api-dev:${{ steps.vars.outputs.sha_short }}
          git add .
          git commit -m "Update image to tag ${{ github.sha }}"
          git push origin main
      
      - name: Status Notify    
        uses: sarisia/actions-status-discord@v1
        if: always()
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ job.status }}
          title: "CI"
